spring:
  profiles:
    include: oauth

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

#  datasource:
#    url: jdbc:mysql://hackathon.ccetd3jlv36v.ap-northeast-2.rds.amazonaws.com/dev?autoReconnect=true
#    username: admin
#    password: jinbeom512
#    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      default_batch_fetch_size: 100
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
